# Generated by Django 3.2.8 on 2021-10-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
