# Generated by Django 3.2.8 on 2021-10-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
