# Generated by Django 3.2.8 on 2021-10-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, default=None, max_length=300)),
                ('heading_1', models.CharField(default=None, max_length=100)),
                ('section_1', models.CharField(default=None, max_length=2000)),
                ('heading_2', models.CharField(blank=True, default=None, max_length=100)),
                ('section_2', models.CharField(blank=True, default=None, max_length=2000)),
                ('heading_3', models.CharField(blank=True, default=None, max_length=100)),
                ('section_3', models.CharField(blank=True, default=None, max_length=2000)),
            ],
        ),
    ]
