# Generated by Django 3.2.8 on 2021-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section_1',
            field=models.TextField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section_2',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section_3',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
    ]
