# Generated by Django 3.2.8 on 2021-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211021_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='heading_1',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
