# Generated by Django 3.2.8 on 2021-10-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_heading_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
