# Generated by Django 3.2.8 on 2021-10-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('size', models.CharField(max_length=50)),
                ('regions', models.CharField(max_length=300)),
                ('about', models.CharField(default=None, max_length=2000)),
            ],
        ),
    ]
