# Generated by Django 3.2.8 on 2021-10-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whale',
            name='image2',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
