# Generated by Django 3.2.8 on 2021-10-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whale',
            name='about',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
