# Generated by Django 3.2.8 on 2021-10-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
